### ISSUE TITLE
Cannot compile cpp client from sample code

### ISSUE THREAD

**Issue by plotters** [RandyAbernethy/ThriftBook#10]
The first example and does not compile. I have boost installed and thrift also:

g++ --std=c++17 hello_client.cpp gen-cpp/HelloSvc.cpp -lthrift -lboost 

In file included from /usr/include/boost/smart_ptr/make_shared.hpp:14,
                 from /usr/include/boost/make_shared.hpp:14,
                 from hello_client.cpp:5:
/usr/include/boost/smart_ptr/make_shared_object.hpp: In instantiation of ‘typename boost::detail::sp_if_not_array<T>::type boost::make_shared(Args&& ...) [with T = apache::thrift::transport::TBufferedTransport; Args = {boost::shared_ptr<apache::thrift::transport::TSocket>&}; typename boost::detail::sp_if_not_array<T>::type = boost::shared_ptr<apache::thrift::transport::TBufferedTransport>]’:
hello_client.cpp:15:62:   required from here
/usr/include/boost/smart_ptr/make_shared_object.hpp:256:5: error: no matching function for call to ‘apache::thrift::transport::TBufferedTransport::TBufferedTransport(boost::shared_ptr<apache::thrift::transport::TSocket>&)’
     ::new( pv ) T( boost::detail::sp_forward<Args>( args )... );
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

I follow the instructions in the book. Thanks in advance for any pointers.

**Comment by RandyAbernethy** [comment]
Hey thanks for the issue post, I'll take a look and come back to you shortly.

**Comment by RandyAbernethy** [comment]
I see the issue. There has been a lot of work going on of late moving thrift to pure C++11 so that boost is not needed. 

This line in file hello_client.cpp is there for just this reason:

`using boost::make_shared;`

It works fine with Thrift 0.10 (which was still using boost::shared_ptr) but I think around 0.12 things moved to std::shared_ptr. Looks like you are building against the dev master, so just change that line to read:

`using std::make_shared;`

Let me know if this fixes your problem!

**Comment by RandyAbernethy** [comment]
I just pushed the above change so now old versions of thrift will not build the code but I commented the old boost version and added an explanation. Pull the fix and see if that doesn't work for you.

Best,
Randy

**Comment by plotters** [comment]
Hi Randy, excellent, thanks it works now. I am indeed using Thrift 0.12 which is installed via the package manager now on Manjaro Linux. Great to know that Thrift is using pure C++11 now. 
Thanks, Bart
